- ============================================================
-- TABLAS MAESTRAS (sin dependencias)
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_ACCIONES" 
   (	"ID_ACCION" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_ACCION" VARCHAR2(50), 
	"DESCRIPCION" VARCHAR2(400), 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	CONSTRAINT "PK_INDAR_ACCIONES" PRIMARY KEY ("ID_ACCION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_CONFIGURATION" 
   (	"COMPONENT" VARCHAR2(100) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"PROPERTY" VARCHAR2(100) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(400), 
	"DESCRIPTION" VARCHAR2(200), 
	"SORT" NUMBER(10,0), 
	 CONSTRAINT "PK_INDAR_CONFIGURATION" PRIMARY KEY ("COMPONENT", "TYPE", "PROPERTY")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_PERSONAS" 
	 ( "ID_PERSONA" NUMBER(10,0) NOT NULL ENABLE, 
 "TIPO_IDENTIFICADOR" VARCHAR2(50), 
 "IDENTIFICADOR" VARCHAR2(100) NOT NULL ENABLE, 
 "NOMBRE" VARCHAR2(100), 
 "APELLIDO1" VARCHAR2(100), 
 "APELLIDO2" VARCHAR2(100), 
 "NOMBRE_COMPLETO" VARCHAR2(200), 
 "EMAIL" VARCHAR2(100), 
 "TELEFONO" VARCHAR2(20), 
 "TIPO_PERSONA" VARCHAR2(20) DEFAULT ''FISICA'' NOT NULL ENABLE, 
 "FECHA_ALTA" DATE NOT NULL ENABLE, 
 "FECHA_MODIFICACION" DATE NOT NULL ENABLE, 
 "FUENTE_ORIGEN" VARCHAR2(30), 
 "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
 "TEMPORAL" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
 "DATOS_ADICIONALES" CLOB, 
	CHECK ("DATOS_ADICIONALES" IS JSON) ENABLE, 
	PRIMARY KEY ("ID_PERSONA")
	 ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_TIPOS_RELACION" 
   (	"ID_TIPO_RELACION" NUMBER(10,0) NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(30), 
	"NOMBRE" VARCHAR2(100), 
	"DESCRIPCION" VARCHAR2(400), 
	"REQUIERE_MAESTRO" NUMBER(1,0) DEFAULT 1, 
	"REQUIERE_APROBACION" NUMBER(1,0) DEFAULT 1, 
	"NIVEL_JERARQUICO" NUMBER(10,0), 
	"ACTIVO" NUMBER(1,0) DEFAULT 1, 
	 PRIMARY KEY ("ID_TIPO_RELACION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_USUARIOS_ESTADOS" 
   (	"ID_ESTADO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_ESTADO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_DOC_ESTADOS"
   (	"ID_ESTADO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_ESTADO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_TIPOS_DOC"
   (	"ID_TIPO_DOC" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_TIPO_DOC")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_AGRUPACIONES"
   (	"ID_AGRUPACION" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(150 CHAR), 
	 PRIMARY KEY ("ID_AGRUPACION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_COMPONENTES"
   (	"ID_COMPONENTE" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(400), 
	"FECHA_ALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ID_COMP_PADRE" NUMBER(10,0), 
	 PRIMARY KEY ("ID_COMPONENTE")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_ESTADOS_EXPEDIENTE"
   (	"ID_ESTADO_EXPEDIENTE" NUMBER(10,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100 CHAR),
	"DESCRIPCION" VARCHAR2(255 CHAR),
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "PK_INDAR_ESTADOS_EXP" PRIMARY KEY ("ID_ESTADO_EXPEDIENTE")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_ESTADO_INST"
   (	"ID_ESTADO" NUMBER(10,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_INDAR_ESTADO_INST" PRIMARY KEY ("ID_ESTADO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_TIPO_EQUIPO"
   (	"ID_TIPO_EQUIPO" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(400) NOT NULL ENABLE, 
	 CONSTRAINT "PK_INDAR_TIPO_EQUIPO" PRIMARY KEY ("ID_TIPO_EQUIPO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_UBICACIONES"
   (	"ID_UBICACION" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"FECHA_ALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_INDAR_UBICACIONES" PRIMARY KEY ("ID_UBICACION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_AGENTES"
   (	"ID_AGENTE" NUMBER NOT NULL ENABLE,
	"TIPO_DOCUMENTO" VARCHAR2(20),
	"NUM_DOCUMENTO" VARCHAR2(20),
	"TIPO_AGENTE" VARCHAR2(20),
	"FEC_CREACION" DATE,
	"USR_CREACION" VARCHAR2(50),
	"FEC_MODIF" DATE,
	 CONSTRAINT "PK_INDAR_AGENTES" PRIMARY KEY ("ID_AGENTE"),
	 CONSTRAINT "UK_INDAR_AG_NUM_DOC" UNIQUE ("NUM_DOCUMENTO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ============================================================
-- TABLAS CON DEPENDENCIAS
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" 
   (	"ID_USUARIO_INDAR" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_PERSONA" NUMBER(10,0), 
	"ID_RUIAR_ENTIDAD" NUMBER(10,0), 
	"ID_TIPO_RELACION" NUMBER(10,0) NOT NULL ENABLE, 
	"ESTADO" NUMBER(10,0), 
	"FECHA_ALTA" DATE, 
	"FECHA_BAJA" DATE, 
	"FECHA_APROBACION" DATE, 
	"USUARIO_APROBACION" NUMBER(10,0), 
	"MOTIVO_BAJA" VARCHAR2(400), 
	"MFE_ULTIMA_SYNC" DATE, 
	"MFE_TOKEN_HASH" VARCHAR2(400), 
	"DATOS_ADICIONALES" CLOB, 
	 CHECK ("DATOS_ADICIONALES" IS JSON) ENABLE, 
	 PRIMARY KEY ("ID_USUARIO_INDAR")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_VERSIONES_APLICACION" 
   (	"ID_VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"NUMERO_VERSION" VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(255), 
	"FECHA_VERSION" DATE NOT NULL ENABLE, 
	"ACTIVO" NUMBER(1,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_VERSION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_AUDITORIA_ACCESOS" 
   (	"ID_AUDITORIA" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_USUARIO_REL" NUMBER(10,0), 
	"SESION_ID" VARCHAR2(100), 
	"TIPO_AUTENTICACION" VARCHAR2(50), 
	"IP_ORIGEN" VARCHAR2(30), 
	"NAVEGADOR" VARCHAR2(100), 
	"DISPOSITIVO" VARCHAR2(100), 
	"FECHA_LOGIN" DATE, 
	"FECHA_LOGOUT" DATE, 
	"DURACION_SEGUNDOS" NUMBER(10,0), 
	 PRIMARY KEY ("ID_AUDITORIA")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_MENU" 
   (	"ID_MENU" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(255), 
	"ORDEN" NUMBER(5,0) NOT NULL ENABLE, 
	"ACTIVO" NUMBER(1,0) NOT NULL ENABLE, 
	"URL" VARCHAR2(200) NOT NULL ENABLE,
	"ID_MENU_PADRE" NUMBER(10,0), 
	"ID_VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_MENU")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" 
   (	"ID_PERMISO_REL_VER" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_TIPO_RELACION" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_MENU" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ACCION" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"FECHA_ALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"FECHA_BAJA" DATE, 
	CONSTRAINT "PK_PERMISOS_REL_VER" PRIMARY KEY ("ID_PERMISO_REL_VER"), 
	CONSTRAINT "UK_PERMISOS_REL_VER" UNIQUE ("ID_TIPO_RELACION", "ID_VERSION", "ID_MENU", "ID_ACCION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/


BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_DOC_USUARIOS_REL"
	(	"ID_DOC_USU_REL" NUMBER(10,0) NOT NULL ENABLE,
		"TIPO_DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE,
		"NOMBRE" VARCHAR2(200) NOT NULL ENABLE,
		"CSV" VARCHAR2(100),
		"DESCRIPCION" VARCHAR2(400),
		"FECHA_MODIFICACION" DATE,
		"FECHA_ALTA" DATE NOT NULL ENABLE,
		"ID_USUARIO_REL_INDAR" NUMBER(10,0) NOT NULL ENABLE,
		"ESTADO" NUMBER(10,0) NOT NULL ENABLE,
		CONSTRAINT "PK_DOC_USU_REL" PRIMARY KEY ("ID_DOC_USU_REL")
	) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_AMBITOS"
   (	"ID_AMBITO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"CODIGO" VARCHAR2(30 CHAR), 
	"DESCRIPCION" VARCHAR2(255 CHAR), 
	"CORRESPONDENCIA_PEA" VARCHAR2(30 CHAR), 
	"RII_DIVISION_C" VARCHAR2(30 CHAR), 
	"RII_DIVISION_B_D" VARCHAR2(30 CHAR), 
	"RII_DIVISION_B_E" VARCHAR2(30 CHAR), 
	"FECHA_ALTA" DATE, 
	"FECHA_BAJA" DATE, 
	"ID_AGRUPACION" NUMBER(10,0), 
	 PRIMARY KEY ("ID_AMBITO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_TRAMITES"
   (	"ID_TRAMITE" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"CODIGO" VARCHAR2(30 CHAR), 
	"DESCRIPCION" VARCHAR2(255 CHAR), 
	"FECHA_ALTA" DATE, 
	"FECHA_BAJA" DATE, 
	"ID_AMBITO" NUMBER(10,0), 
	 PRIMARY KEY ("ID_TRAMITE")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_VERSION_COMP"
   (	"ID_VERSION_COMP" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_COMPONENTE" NUMBER(10,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"ESTRUCTURA_JSON" CLOB, 
	"VALIDACION_DATOS" CLOB, 
	 CHECK ("ESTRUCTURA_JSON" IS JSON) ENABLE, 
	 CHECK ("VALIDACION_DATOS" IS JSON) ENABLE, 
	 PRIMARY KEY ("ID_VERSION_COMP"), 
	 CONSTRAINT "UK_VERSION_COMP_VER" UNIQUE ("ID_COMPONENTE", "VERSION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_VERSION_TRAMITES"
   (	"ID_VERSION_TRAMITE" NUMBER(10,0), 
	"ID_TRAMITE" NUMBER(10,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) NOT NULL ENABLE, 
	"PROCEDIMIENTO" VARCHAR2(100 CHAR), 
	"ORGANO" VARCHAR2(100 CHAR), 
	"DESCRIPCION" VARCHAR2(255 CHAR), 
	"FECHA_ALTA" DATE, 
	"FECHA_BAJA" DATE, 
	 PRIMARY KEY ("ID_VERSION_TRAMITE")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_TRAMITES_DOCUMENTOS"
   (	"ID_TRAMITE_DOC" NUMBER(10,0), 
	"ID_VERSION_TRAMITE" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_TIPO_DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDEN_DOC" NUMBER(5,0), 
	"SE_FIRMA" NUMBER(1,0), 
	"SE_SELLA" NUMBER(1,0), 
	"OBLIGATORIO" NUMBER(1,0), 
	"REPETIBLE" NUMBER(1,0), 
	"ID_VERSION_COMPONENTE" NUMBER(10,0), 
	 PRIMARY KEY ("ID_TRAMITE_DOC")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_EXPEDIENTES"
   (	"ID_EXPEDIENTE" NUMBER(10,0), 
	"FECHA_ALTA" DATE, 
	"FECHA_FIN" DATE, 
	"NUMERO_EXP" VARCHAR2(100 CHAR), 
	"ESTADO" NUMBER(10,0), 
	 PRIMARY KEY ("ID_EXPEDIENTE")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_EMPLAZAMIENTO_DATOS"
   (	"ID_EMPLAZAMIENTO_DATOS" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_VERSION_COMP" NUMBER(10,0) NOT NULL ENABLE, 
	"DATOS_EMPLAZAMIENTO" CLOB NOT NULL ENABLE, 
	"ID_UBICACION" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_INDAR_EMPL_DATOS" PRIMARY KEY ("ID_EMPLAZAMIENTO_DATOS")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_EXPE_COMP_DATOS"
   (	"ID_EXPE_COMP_DATOS" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_EXPEDIENTE" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_VERSION_COMP" NUMBER(10,0) NOT NULL ENABLE, 
	"DATOS_EXPEDIENTE_COMPONENTE" CLOB, 
	"CAUDAL_GN" NUMBER GENERATED ALWAYS AS (
		CASE "ID_VERSION_COMP" WHEN 7 THEN
			TO_NUMBER(JSON_VALUE("DATOS_EXPEDIENTE_COMPONENTE" FORMAT JSON, '$.caudal'
			RETURNING VARCHAR2(4000) NULL ON ERROR))
		END) VIRTUAL,
	"RESULTADO_INSP" VARCHAR2(4000) GENERATED ALWAYS AS (
		CASE "ID_VERSION_COMP" WHEN 8 THEN
			JSON_VALUE("DATOS_EXPEDIENTE_COMPONENTE" FORMAT JSON, '$.resultado'
			RETURNING VARCHAR2(4000) NULL ON ERROR)
		END) VIRTUAL,
	 CHECK ("DATOS_EXPEDIENTE_COMPONENTE" IS JSON) ENABLE, 
	 PRIMARY KEY ("ID_EXPE_COMP_DATOS")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_INSTALACION"
   (	"ID_INSTALACION" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_EMPLAZAMIENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ESTADO_INST" NUMBER(10,0) NOT NULL ENABLE, 
	"NUMERO" VARCHAR2(100), 
	"FECHA_ALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_BAJA" DATE, 
	"FECHA_ULTIMA_MOD" DATE, 
	"DATOS_INSTALACION" CLOB NOT NULL ENABLE, 
	 CONSTRAINT "PK_INDAR_INSTALACION" PRIMARY KEY ("ID_INSTALACION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_EQUIPOS"
   (	"ID_EQUIPO" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_INSTALACION" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_EQUIPO" NUMBER(10,0) NOT NULL ENABLE, 
	"FECHA_ALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_BAJA" DATE, 
	"FECHA_ULTIMA_MOD" DATE, 
	"DATOS_EQUIPO" CLOB NOT NULL ENABLE, 
	 CONSTRAINT "PK_INDAR_EQUIPOS" PRIMARY KEY ("ID_EQUIPO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_EXPEDIENTES_INSTALACIONES"
   (	"ID_EXPE_INST" NUMBER(10,0), 
	"ID_EXPEDIENTE" NUMBER(10,0), 
	"ID_INSTALACION" NUMBER(10,0), 
	 PRIMARY KEY ("ID_EXPE_INST")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_AGENTES_VERSION"
   (	"ID_AGENTE_VER" NUMBER NOT NULL ENABLE,
	"ID_AGENTE" NUMBER NOT NULL ENABLE,
	"NUM_VERSION" NUMBER,
	"NOMBRE_RAZON_SOC" VARCHAR2(200),
	"APELLIDO1" VARCHAR2(100),
	"APELLIDO2" VARCHAR2(100),
	"EMAIL" VARCHAR2(200),
	"TELEFONO" VARCHAR2(30),
	"DIRECCION" VARCHAR2(500),
	"FEC_INI_VIGENCIA" DATE,
	"FEC_FIN_VIGENCIA" DATE,
	"MOTIVO_CAMBIO" VARCHAR2(500),
	"FEC_CREACION" DATE,
	"USR_CREACION" VARCHAR2(50),
	 CONSTRAINT "PK_INDAR_AG_VER" PRIMARY KEY ("ID_AGENTE_VER"),
	 CONSTRAINT "UK_IAV_AG_NUMVER" UNIQUE ("ID_AGENTE", "NUM_VERSION")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_DOCUMENTO_AGENTES"
   (	"ID_DOCUMENTO" NUMBER NOT NULL ENABLE,
	"ID_AGENTE" NUMBER NOT NULL ENABLE,
	"TIPO_DOCUMENTO" VARCHAR2(20),
	"NUM_DOCUMENTO" VARCHAR2(20),
	"FEC_REGISTRO" DATE,
	"FEC_BAJA" DATE,
	"OBS_DOCUMENTO" VARCHAR2(200),
	"FEC_CREACION" DATE,
	"USR_CREACION" VARCHAR2(50),
	 CONSTRAINT "PK_INDAR_DOCUMENTO_AGENTES" PRIMARY KEY ("ID_DOCUMENTO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_EXP_AGENTES_VER"
   (	"ID_EXP_AG_VER" NUMBER NOT NULL ENABLE,
	"ID_EXPEDIENTE" NUMBER NOT NULL ENABLE,
	"ID_AGENTE" NUMBER NOT NULL ENABLE,
	"ID_AGENTE_VER" NUMBER NOT NULL ENABLE,
	"ROL_AGENTE" VARCHAR2(30),
	"FEC_ASIGNACION" DATE,
	"FEC_BAJA" DATE,
	"FEC_CREACION" DATE,
	"USR_CREACION" VARCHAR2(50),
	 CONSTRAINT "PK_INDAR_EXP_AG_VER" PRIMARY KEY ("ID_EXP_AG_VER")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP"
   (	"ID_V_PANTALLA_COMP" NUMBER(10,0) NOT NULL ENABLE,
     "ID_VERSION_PANTALLA" NUMBER(10,0),
	 "ID_VERSION_COMPONENTE" NUMBER(10,0),
	 "ORDEN" NUMBER(5,0) NOT NULL ENABLE,	
	 CONSTRAINT "PK_VER_PANTALLA_COMP" PRIMARY KEY ("ID_V_PANTALLA_COMP")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INDAR_OWN.INDAR_TM_VERSION_PANTALLAS (
	ID_V_PANTALLA NUMBER(10,0),
	VERSION NUMBER(10,0),
	ID_PANTALLA NUMBER(10,0),
	JAVASCRIPT CLOB,
	CONSTRAINT PK_VER_PANTALLA PRIMARY KEY (ID_V_PANTALLA),
	CONSTRAINT SYS_C00105185 CHECK ("ID_V_PANTALLA" IS NOT NULL),
	CONSTRAINT SYS_C00105186 CHECK ("VERSION" IS NOT NULL),
	CONSTRAINT SYS_C00105187 CHECK ("ID_PANTALLA" IS NOT NULL)
) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_PANTALLAS"
   (	"ID_PANTALLA" NUMBER(10,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(150),
	"DESCRIPCION" VARCHAR2(300),
	"FECHA_ALTA" DATE,
	"ID_PANTALLA_PADRE" NUMBER(10,0),
	 CONSTRAINT "PK_INDAR_TM_PANTALLAS" PRIMARY KEY ("ID_PANTALLA")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS"
   (	"ID_ESTADO_FLUJO" NUMBER(10,0) NOT NULL ENABLE,
	"ID_V_PANTALLA_COMP" NUMBER(10,0) NOT NULL ENABLE,
	"ID_ESTADO_ACTUAL" NUMBER(10,0) NOT NULL ENABLE,
	"ID_ESTADO_SIGUIENTE" NUMBER(10,0) NOT NULL ENABLE,
	"EVENTO_ENUM" VARCHAR2(100),
	"ID_TIPO_DOC" NUMBER(10,0),
	"ID_USU_REL" NUMBER(10,0),
	 CONSTRAINT "PK_TM_ESTADOS_FLUJOS" PRIMARY KEY ("ID_ESTADO_FLUJO")
   ) TABLESPACE "INDAR_DAT"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ============================================================
-- FOREIGN KEYS - Se crean después de todas las tablas
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_AUDITORIA_ACCESOS" ADD CONSTRAINT "FK_INDAR_AUD_USUARIO_REL" FOREIGN KEY ("ID_USUARIO_REL") REFERENCES "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ("ID_USUARIO_INDAR") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ADD CONSTRAINT "FK_INDAR_USUREL_TIPO_REL" FOREIGN KEY ("ID_TIPO_RELACION") REFERENCES "INDAR_OWN"."INDAR_TM_TIPOS_RELACION" ("ID_TIPO_RELACION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ADD CONSTRAINT "FK_INDAR_USUREL_ESTADOS" FOREIGN KEY ("ESTADO") REFERENCES "INDAR_OWN"."INDAR_TM_USUARIOS_ESTADOS" ("ID_ESTADO") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ADD CONSTRAINT "FK_INDAR_USUREL_PERSONA" FOREIGN KEY ("ID_PERSONA") REFERENCES "INDAR_OWN"."INDAR_PERSONAS" ("ID_PERSONA") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_MENU" ADD CONSTRAINT "FK_INDAR_MENU_PADRE" FOREIGN KEY ("ID_MENU_PADRE") REFERENCES "INDAR_OWN"."INDAR_MENU" ("ID_MENU") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_MENU" ADD CONSTRAINT "FK_INDAR_MENU_VERSION" FOREIGN KEY ("ID_VERSION") REFERENCES "INDAR_OWN"."INDAR_VERSIONES_APLICACION" ("ID_VERSION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ADD CONSTRAINT "FK_PERM_TIPO_REL" FOREIGN KEY ("ID_TIPO_RELACION") REFERENCES "INDAR_OWN"."INDAR_TM_TIPOS_RELACION" ("ID_TIPO_RELACION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ADD CONSTRAINT "FK_PERM_VERSION" FOREIGN KEY ("ID_VERSION") REFERENCES "INDAR_OWN"."INDAR_VERSIONES_APLICACION" ("ID_VERSION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ADD CONSTRAINT "FK_PERM_MENU" FOREIGN KEY ("ID_MENU") REFERENCES "INDAR_OWN"."INDAR_MENU" ("ID_MENU") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ADD CONSTRAINT "FK_PERM_ACCION" FOREIGN KEY ("ID_ACCION") REFERENCES "INDAR_OWN"."INDAR_ACCIONES" ("ID_ACCION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_DOC_USUARIOS_REL" ADD CONSTRAINT "FK_DOCUSUREL_USUARIO" FOREIGN KEY ("ID_USUARIO_REL_INDAR") REFERENCES "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ("ID_USUARIO_INDAR") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_DOC_USUARIOS_REL" ADD CONSTRAINT "FK_DOCUSUREL_ESTADO" FOREIGN KEY ("ESTADO") REFERENCES "INDAR_OWN"."INDAR_TM_DOC_ESTADOS" ("ID_ESTADO") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_DOC_USUARIOS_REL" ADD CONSTRAINT "FK_DOCUSUREL_TIPO_DOC" FOREIGN KEY ("TIPO_DOCUMENTO") REFERENCES "INDAR_OWN"."INDAR_TM_TIPOS_DOC" ("ID_TIPO_DOC") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_AMBITOS" ADD CONSTRAINT "FK_TM_AMBITOS_AGRUP" FOREIGN KEY ("ID_AGRUPACION") REFERENCES "INDAR_OWN"."INDAR_TM_AGRUPACIONES" ("ID_AGRUPACION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_TRAMITES" ADD CONSTRAINT "FK_TM_TRAMITES_AMBITO" FOREIGN KEY ("ID_AMBITO") REFERENCES "INDAR_OWN"."INDAR_TM_AMBITOS" ("ID_AMBITO") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_VERSION_COMP" ADD CONSTRAINT "FK_VER_COMP_COMPONENTE" FOREIGN KEY ("ID_COMPONENTE") REFERENCES "INDAR_OWN"."INDAR_TM_COMPONENTES" ("ID_COMPONENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_VERSION_TRAMITES" ADD CONSTRAINT "FK_VERTRAM_TRAMITE" FOREIGN KEY ("ID_TRAMITE") REFERENCES "INDAR_OWN"."INDAR_TM_TRAMITES" ("ID_TRAMITE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_TRAMITES_DOCUMENTOS" ADD CONSTRAINT "FK_TRAMDOC_VERTRAM" FOREIGN KEY ("ID_VERSION_TRAMITE") REFERENCES "INDAR_OWN"."INDAR_TM_VERSION_TRAMITES" ("ID_VERSION_TRAMITE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_TRAMITES_DOCUMENTOS" ADD CONSTRAINT "FK_TRAMDOC_TIPODOC" FOREIGN KEY ("ID_TIPO_DOCUMENTO") REFERENCES "INDAR_OWN"."INDAR_TM_TIPOS_DOC" ("ID_TIPO_DOC") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EXPEDIENTES" ADD CONSTRAINT "FK_EXPEDIENTE_ESTADO" FOREIGN KEY ("ESTADO") REFERENCES "INDAR_OWN"."INDAR_TM_ESTADOS_EXPEDIENTE" ("ID_ESTADO_EXPEDIENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EMPLAZAMIENTO_DATOS" ADD CONSTRAINT "FK_EMPL_DATOS_VER_COMP" FOREIGN KEY ("ID_VERSION_COMP") REFERENCES "INDAR_OWN"."INDAR_TM_VERSION_COMP" ("ID_VERSION_COMP") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EMPLAZAMIENTO_DATOS" ADD CONSTRAINT "FK_UBICACION_EMPLAZAMIENTO" FOREIGN KEY ("ID_UBICACION") REFERENCES "INDAR_OWN"."INDAR_UBICACIONES" ("ID_UBICACION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EXPE_COMP_DATOS" ADD CONSTRAINT "FK_EXPE_COMP_VER" FOREIGN KEY ("ID_VERSION_COMP") REFERENCES "INDAR_OWN"."INDAR_TM_VERSION_COMP" ("ID_VERSION_COMP") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_INSTALACION" ADD CONSTRAINT "FK_INST_EMPLAZAMIENTO" FOREIGN KEY ("ID_EMPLAZAMIENTO") REFERENCES "INDAR_OWN"."INDAR_EMPLAZAMIENTO_DATOS" ("ID_EMPLAZAMIENTO_DATOS") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_INSTALACION" ADD CONSTRAINT "FK_INST_ESTADO" FOREIGN KEY ("ID_ESTADO_INST") REFERENCES "INDAR_OWN"."INDAR_TM_ESTADO_INST" ("ID_ESTADO") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EQUIPOS" ADD CONSTRAINT "FK_EQUIPO_INST" FOREIGN KEY ("ID_INSTALACION") REFERENCES "INDAR_OWN"."INDAR_INSTALACION" ("ID_INSTALACION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EQUIPOS" ADD CONSTRAINT "FK_EQUIPO_TIPO" FOREIGN KEY ("TIPO_EQUIPO") REFERENCES "INDAR_OWN"."INDAR_TM_TIPO_EQUIPO" ("ID_TIPO_EQUIPO") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EXPEDIENTES_INSTALACIONES" ADD CONSTRAINT "FK_EXPEDIENTE" FOREIGN KEY ("ID_EXPEDIENTE") REFERENCES "INDAR_OWN"."INDAR_EXPEDIENTES" ("ID_EXPEDIENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EXPEDIENTES_INSTALACIONES" ADD CONSTRAINT "FK_INSTALACIONES" FOREIGN KEY ("ID_INSTALACION") REFERENCES "INDAR_OWN"."INDAR_INSTALACION" ("ID_INSTALACION") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP" ADD CONSTRAINT "FK_VER_PANT_COMP_PANTALLA" FOREIGN KEY ("ID_VERSION_PANTALLA") REFERENCES "INDAR_OWN"."INDAR_TM_VERSION_PANTALLAS" ("ID_V_PANTALLA") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_PANTALLAS" ADD CONSTRAINT "FK_PANTALLAS_PADRE" FOREIGN KEY ("ID_PANTALLA_PADRE") REFERENCES "INDAR_OWN"."INDAR_TM_PANTALLAS" ("ID_PANTALLA") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ADD CONSTRAINT "FK_ESTADOS_FL_PANTALLA" FOREIGN KEY ("ID_V_PANTALLA_COMP") REFERENCES "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP" ("ID_V_PANTALLA_COMP") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

-- FK para ID_VERSION_COMPONENTE en INDAR_TM_VERSION_PANTALLA_COMP
BEGIN
	EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP" ADD CONSTRAINT "FK_ESTADOS_FL_V_COMP" FOREIGN KEY ("ID_VERSION_COMPONENTE") REFERENCES "INDAR_OWN"."INDAR_TM_VERSION_COMP" ("ID_VERSION_COMP") ENABLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -2264, -2275) THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ADD CONSTRAINT "FK_ESTADOS_FL_ESTADO_ACT" FOREIGN KEY ("ID_ESTADO_ACTUAL") REFERENCES "INDAR_OWN"."INDAR_TM_ESTADOS_EXPEDIENTE" ("ID_ESTADO_EXPEDIENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ADD CONSTRAINT "FK_ESTADOS_FL_ESTADO_SIG" FOREIGN KEY ("ID_ESTADO_SIGUIENTE") REFERENCES "INDAR_OWN"."INDAR_TM_ESTADOS_EXPEDIENTE" ("ID_ESTADO_EXPEDIENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ADD CONSTRAINT "FK_ESTADOS_FL_TIPO_DOC" FOREIGN KEY ("ID_TIPO_DOC") REFERENCES "INDAR_OWN"."INDAR_TM_TIPOS_DOC" ("ID_TIPO_DOC") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ADD CONSTRAINT "FK_ESTADOS_FL_USU_REL" FOREIGN KEY ("ID_USU_REL") REFERENCES "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ("ID_USUARIO_INDAR") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_VERSION_PANTALLAS" ADD CONSTRAINT "FK_VER_PANT_COMP" FOREIGN KEY ("ID_V_PANTALLA_COMP") REFERENCES "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP" ("ID_V_PANTALLA_COMP") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_AGENTES_VERSION" ADD CONSTRAINT "FK_IAV_AGENTE" FOREIGN KEY ("ID_AGENTE") REFERENCES "INDAR_OWN"."INDAR_AGENTES" ("ID_AGENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_DOCUMENTO_AGENTES" ADD CONSTRAINT "FK_IDOC_AGENTE" FOREIGN KEY ("ID_AGENTE") REFERENCES "INDAR_OWN"."INDAR_AGENTES" ("ID_AGENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EXP_AGENTES_VER" ADD CONSTRAINT "FK_IEAV_EXP" FOREIGN KEY ("ID_EXPEDIENTE") REFERENCES "INDAR_OWN"."INDAR_EXPEDIENTES" ("ID_EXPEDIENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EXP_AGENTES_VER" ADD CONSTRAINT "FK_IEAV_AG" FOREIGN KEY ("ID_AGENTE") REFERENCES "INDAR_OWN"."INDAR_AGENTES" ("ID_AGENTE") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_EXP_AGENTES_VER" ADD CONSTRAINT "FK_IEAV_AG_VER" FOREIGN KEY ("ID_AGENTE_VER") REFERENCES "INDAR_OWN"."INDAR_AGENTES_VERSION" ("ID_AGENTE_VER") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE "INDAR_OWN"."INDAR_TM_VERSION_PANTALLAS" ADD CONSTRAINT "FK_V_PANT_PANTALLAS" FOREIGN KEY ("ID_PANTALLA") REFERENCES "INDAR_OWN"."INDAR_TM_PANTALLAS" ("ID_PANTALLA") ENABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-2264,-2275) THEN RAISE; END IF; END;
/


-- ============================================================
-- COMENTARIOS DE TABLAS Y COLUMNAS
-- ============================================================

COMMENT ON TABLE INDAR_OWN.INDAR_ACCIONES IS 'Tabla de acciones disponibles en el sistema INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.ID_ACCION IS 'Clave primaria de acción';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.TIPO_ACCION IS 'Tipo de acción (CONSULTAR, CREAR, EDITAR, ELIMINAR, etc.)';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.DESCRIPCION IS 'Descripción de la acción';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.ACTIVO IS 'Indica si la acción está activa';

COMMENT ON TABLE INDAR_OWN.INDAR_AUDITORIA_ACCESOS IS 'Tabla con la auditoria de accesos de usuarios INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.ID_AUDITORIA IS 'Clave primaria de auditoría de acceso';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.ID_USUARIO_REL IS 'Usuario que accede';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.SESION_ID IS 'Identificador de sesión de login';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.TIPO_AUTENTICACION IS 'Tipo de autenticación utilizada';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.IP_ORIGEN IS 'IP de origen del acceso';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.NAVEGADOR IS 'Navegador utilizado en el acceso';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.DISPOSITIVO IS 'Dispositivo utilizado en el acceso';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.FECHA_LOGIN IS 'Fecha y hora de login';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.FECHA_LOGOUT IS 'Fecha y hora de logout';
COMMENT ON COLUMN INDAR_OWN.INDAR_AUDITORIA_ACCESOS.DURACION_SEGUNDOS IS 'Duración de la sesión en segundos';

COMMENT ON TABLE INDAR_OWN.INDAR_CONFIGURATION IS 'Tabla con la configuracion de la aplicacion';
COMMENT ON COLUMN INDAR_OWN.INDAR_CONFIGURATION.COMPONENT IS 'Componente de la plataforma a la que referencia';
COMMENT ON COLUMN INDAR_OWN.INDAR_CONFIGURATION."TYPE" IS 'Tipo de configuración a la que referencia';
COMMENT ON COLUMN INDAR_OWN.INDAR_CONFIGURATION.PROPERTY IS 'Propiedad de configuración a la que referencia';
COMMENT ON COLUMN INDAR_OWN.INDAR_CONFIGURATION.VALUE IS 'Valor de la configuración';
COMMENT ON COLUMN INDAR_OWN.INDAR_CONFIGURATION.DESCRIPTION IS 'Descripción de la configuración';
COMMENT ON COLUMN INDAR_OWN.INDAR_CONFIGURATION.SORT IS 'Orden de relevancia';

COMMENT ON TABLE INDAR_OWN.INDAR_MENU IS 'Tabla de menús de la aplicación INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.ID_MENU IS 'Clave primaria de menú';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.NOMBRE IS 'Nombre del menú';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.DESCRIPCION IS 'Descripción del menú';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.ORDEN IS 'Orden de visualización del menú';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.ACTIVO IS 'Indica si el menú está activo';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.URL IS 'URL asociada al menú, si es un menú padre no debe tener URL';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.ID_MENU_PADRE IS 'Menú padre (jerarquía)';
COMMENT ON COLUMN INDAR_OWN.INDAR_MENU.ID_VERSION IS 'Versión de aplicación asociada';

COMMENT ON TABLE INDAR_OWN.INDAR_PERSONAS IS 'Tabla de personas en INDAR_OWN';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.ID_PERSONA IS 'Clave primaria de persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.TIPO_IDENTIFICADOR IS 'Tipo de identificador de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.IDENTIFICADOR IS 'Documento que lo identifique univocamente DNI, NIF,VAT...';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.NOMBRE IS 'Nombre de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.APELLIDO1 IS 'Primer apellido de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.APELLIDO2 IS 'Segundo apellido de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.NOMBRE_COMPLETO IS 'Nombre completo de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.EMAIL IS 'Correo electrónico de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.TELEFONO IS 'Teléfono de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.TIPO_PERSONA IS 'Tipo de persona FISICA o JURIDICA';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.FECHA_ALTA IS 'Fecha de alta de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.FECHA_MODIFICACION IS 'Fecha de modificación de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.FUENTE_ORIGEN IS 'Fuente de origen de la persona';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.ACTIVO IS 'Indica si la persona está activa';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.TEMPORAL IS 'Indica si no estan en las tablas de RUIAR y hay que usarlo mientras se da de alta el expedente';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERSONAS.DATOS_ADICIONALES IS 'Datos adicionales en formato JSON';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_TIPOS_RELACION IS 'Tabla de tipos de relación/perfil en INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.ID_TIPO_RELACION IS 'Clave primaria del tipo de relación';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.CODIGO IS 'Código del perfil de usuario';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.NOMBRE IS 'Nombre del perfil de usuario';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.DESCRIPCION IS 'Descripción del tipo de relación';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.REQUIERE_MAESTRO IS 'Indica si requiere maestro';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.REQUIERE_APROBACION IS 'Indica si requiere aprobación';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.NIVEL_JERARQUICO IS 'Nivel jerárquico del tipo de relación';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_RELACION.ACTIVO IS 'Indica si el tipo de relación está activo';

COMMENT ON TABLE INDAR_OWN.INDAR_USUARIOS_RELACIONADOS IS 'Tabla de usuarios relacionados en INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.ID_USUARIO_INDAR IS 'Clave primaria de usuario relacionado';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.ID_PERSONA IS 'Identificador de la persona en INDAR_PERSONAS, para los usuarios de titular y empresa(atonomos) este campo estara a null';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.ID_RUIAR_ENTIDAD IS 'Entidad relacionada (cross-schema)';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.ID_TIPO_RELACION IS 'Tipo de relación/perfil';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.ESTADO IS 'Estado del usuario relacionado';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.FECHA_ALTA IS 'Fecha de alta del usuario relacionado';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.FECHA_BAJA IS 'Fecha de baja del usuario relacionado';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.FECHA_APROBACION IS 'Fecha de aprobación del usuario';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.USUARIO_APROBACION IS 'Usuario que aprueba la relación';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.MOTIVO_BAJA IS 'Motivo de la baja del usuario';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.MFE_ULTIMA_SYNC IS 'Fecha de última sincronización MFE';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.MFE_TOKEN_HASH IS 'Hash del token MFE';
COMMENT ON COLUMN INDAR_OWN.INDAR_USUARIOS_RELACIONADOS.DATOS_ADICIONALES IS 'Datos adicionales en formato JSON para información complementaria del usuario';

COMMENT ON TABLE INDAR_OWN.INDAR_VERSIONES_APLICACION IS 'Tabla de versiones de la aplicación INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_VERSIONES_APLICACION.ID_VERSION IS 'Clave primaria de versión de aplicación';
COMMENT ON COLUMN INDAR_OWN.INDAR_VERSIONES_APLICACION.NUMERO_VERSION IS 'Número de versión';
COMMENT ON COLUMN INDAR_OWN.INDAR_VERSIONES_APLICACION.DESCRIPCION IS 'Descripción de la versión';
COMMENT ON COLUMN INDAR_OWN.INDAR_VERSIONES_APLICACION.FECHA_VERSION IS 'Fecha de la versión';
COMMENT ON COLUMN INDAR_OWN.INDAR_VERSIONES_APLICACION.ACTIVO IS 'Indica si la versión está activa';

COMMENT ON TABLE INDAR_OWN.INDAR_ACCIONES IS 'Catálogo de acciones que se pueden realizar sobre los menús de INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.ID_ACCION IS 'Clave primaria de la acción';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.TIPO_ACCION IS 'Tipo de acción: CREAR, EDITAR, ELIMINAR, FIRMAR, APROBAR, VER, EXPORTAR, etc.';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.DESCRIPCION IS 'Descripción detallada de la acción';
COMMENT ON COLUMN INDAR_OWN.INDAR_ACCIONES.ACTIVO IS 'Indica si la acción está activa (1) o inactiva (0)';

COMMENT ON TABLE INDAR_OWN.INDAR_PERMISOS_REL_VERSION IS 'Permisos por perfil, versión, menú y acción';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.ID_PERMISO_REL_VER IS 'Clave primaria del permiso';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.ID_TIPO_RELACION IS 'Perfil de usuario';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.ID_VERSION IS 'Versión de la aplicación';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.ID_MENU IS 'Menú o funcionalidad';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.ID_ACCION IS 'Acción permitida';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.ACTIVO IS 'Indica si el permiso está activo';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.FECHA_ALTA IS 'Fecha de alta del permiso';
COMMENT ON COLUMN INDAR_OWN.INDAR_PERMISOS_REL_VERSION.FECHA_BAJA IS 'Fecha de baja del permiso';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_DOC_ESTADOS IS 'Tabla de estados de documentos en INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_DOC_ESTADOS.ID_ESTADO IS 'Clave primaria del estado de documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_DOC_ESTADOS.NOMBRE IS 'Nombre del estado de documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_DOC_ESTADOS.DESCRIPCION IS 'Descripción del estado de documento';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS IS 'Tabla de estados de usuario en INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS.ID_ESTADO IS 'Clave primaria del estado de usuario';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS.NOMBRE IS 'Nombre del estado de usuario';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS.DESCRIPCION IS 'Descripción del estado de usuario';

COMMENT ON TABLE INDAR_OWN.INDAR_DOC_USUARIOS_REL IS 'Documentos asociados a usuarios relacionados en INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.ID_DOC_USU_REL IS 'Clave primaria del documento de usuario relacionado';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.TIPO_DOCUMENTO IS 'Tipo de documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.NOMBRE IS 'Nombre del documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.CSV IS 'Código CSV del documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.DESCRIPCION IS 'Descripción del documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.FECHA_MODIFICACION IS 'Fecha de modificación del documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.FECHA_ALTA IS 'Fecha de alta del documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.ID_USUARIO_REL_INDAR IS 'Usuario relacionado al que pertenece el documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_DOC_USUARIOS_REL.ESTADO IS 'Estado del documento (FK a INDAR_TM_DOC_ESTADOS)';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_TIPOS_DOC IS 'Tabla maestra de tipos de documentos en INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_DOC.ID_TIPO_DOC IS 'Clave primaria del tipo de documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_DOC.NOMBRE IS 'Nombre del tipo de documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPOS_DOC.DESCRIPCION IS 'Descripción del tipo de documento';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_AGRUPACIONES IS 'Agrupaciones de ámbitos técnicos';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_AGRUPACIONES.ID_AGRUPACION IS 'Clave primaria de la agrupación';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_AGRUPACIONES.NOMBRE IS 'Nombre de la agrupación';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_AMBITOS IS 'Ámbitos técnicos del sistema (AE, BT, EP, GLP, etc.)';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_AMBITOS.ID_AMBITO IS 'Clave primaria del ámbito';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_AMBITOS.NOMBRE IS 'Nombre del ámbito técnico';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_AMBITOS.CODIGO IS 'Código corto del ámbito';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_AMBITOS.DESCRIPCION IS 'Descripción del ámbito';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_AMBITOS.ID_AGRUPACION IS 'Agrupación a la que pertenece el ámbito';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_TRAMITES IS 'Trámites disponibles por ámbito técnico';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES.ID_TRAMITE IS 'Clave primaria del trámite';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES.NOMBRE IS 'Nombre del trámite';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES.CODIGO IS 'Código del trámite';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES.ID_AMBITO IS 'Ámbito al que pertenece el trámite';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_VERSION_TRAMITES IS 'Versiones de trámites con su configuración';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_TRAMITES.ID_VERSION_TRAMITE IS 'Clave primaria de la versión del trámite';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_TRAMITES.ID_TRAMITE IS 'Trámite al que pertenece la versión';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_TRAMITES.VERSION IS 'Número de versión del trámite';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_TRAMITES.PROCEDIMIENTO IS 'Procedimiento administrativo asociado';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_TRAMITES.ORGANO IS 'Órgano competente del trámite';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_TRAMITES_DOCUMENTOS IS 'Documentos asociados a versiones de trámites';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES_DOCUMENTOS.ID_TRAMITE_DOC IS 'Clave primaria del documento de trámite';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES_DOCUMENTOS.ID_VERSION_TRAMITE IS 'Versión del trámite';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES_DOCUMENTOS.ID_TIPO_DOCUMENTO IS 'Tipo de documento';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES_DOCUMENTOS.OBLIGATORIO IS 'Indica si el documento es obligatorio';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES_DOCUMENTOS.REPETIBLE IS 'Indica si el documento es repetible';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TRAMITES_DOCUMENTOS.ID_VERSION_COMPONENTE IS 'Versión del componente asociado al documento';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_COMPONENTES IS 'Tabla maestra de componentes dinámicos del sistema';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_COMPONENTES.ID_COMPONENTE IS 'Clave primaria del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_COMPONENTES.NOMBRE IS 'Nombre descriptivo del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_COMPONENTES.DESCRIPCION IS 'Descripción detallada del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_COMPONENTES.FECHA_ALTA IS 'Fecha de creación del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_COMPONENTES.ID_COMP_PADRE IS 'Componente padre para jerarquías de componentes';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_VERSION_COMP IS 'Versiones de componentes con estructura JSON y validaciones';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_COMP.ID_VERSION_COMP IS 'Clave primaria de la versión del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_COMP.ID_COMPONENTE IS 'Componente al que pertenece esta versión';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_COMP.VERSION IS 'Número de versión correlativo del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_COMP.ESTRUCTURA_JSON IS 'Estructura JSON que define los campos del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_COMP.VALIDACION_DATOS IS 'JSON con validaciones jQuery para los datos del formulario';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE IS 'Estados posibles de los expedientes';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE.ID_ESTADO_EXPEDIENTE IS 'Clave primaria del estado del expediente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE.NOMBRE IS 'Nombre del estado del expediente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE.DESCRIPCION IS 'Descripción del estado';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE.ACTIVO IS 'Indica si el estado está activo (1) o inactivo (0)';

COMMENT ON TABLE INDAR_OWN.INDAR_EXPEDIENTES IS 'Expedientes del sistema INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES.ID_EXPEDIENTE IS 'Clave primaria del expediente';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES.NUMERO_EXP IS 'Número de expediente';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES.ESTADO IS 'Estado actual del expediente';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES.FECHA_ALTA IS 'Fecha de creación del expediente';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES.FECHA_FIN IS 'Fecha de finalización del expediente';

COMMENT ON TABLE INDAR_OWN.INDAR_EXPE_COMP_DATOS IS 'Datos de componentes rellenados en expedientes';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPE_COMP_DATOS.ID_EXPE_COMP_DATOS IS 'Clave primaria del registro';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPE_COMP_DATOS.ID_EXPEDIENTE IS 'Expediente al que pertenecen los datos del componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPE_COMP_DATOS.ID_VERSION_COMP IS 'Versión del componente utilizada';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPE_COMP_DATOS.DATOS_EXPEDIENTE_COMPONENTE IS 'Datos JSON del formulario del componente';

COMMENT ON TABLE INDAR_OWN.INDAR_UBICACIONES IS 'Ubicaciones geográficas del sistema';
COMMENT ON COLUMN INDAR_OWN.INDAR_UBICACIONES.ID_UBICACION IS 'Clave primaria de la ubicación';
COMMENT ON COLUMN INDAR_OWN.INDAR_UBICACIONES.NOMBRE IS 'Nombre de la ubicación';
COMMENT ON COLUMN INDAR_OWN.INDAR_UBICACIONES.FECHA_ALTA IS 'Fecha de alta de la ubicación';

COMMENT ON TABLE INDAR_OWN.INDAR_EMPLAZAMIENTO_DATOS IS 'Datos de emplazamiento de instalaciones';
COMMENT ON COLUMN INDAR_OWN.INDAR_EMPLAZAMIENTO_DATOS.ID_EMPLAZAMIENTO_DATOS IS 'Clave primaria del emplazamiento';
COMMENT ON COLUMN INDAR_OWN.INDAR_EMPLAZAMIENTO_DATOS.ID_VERSION_COMP IS 'Versión del componente de emplazamiento';
COMMENT ON COLUMN INDAR_OWN.INDAR_EMPLAZAMIENTO_DATOS.DATOS_EMPLAZAMIENTO IS 'Datos JSON del emplazamiento';
COMMENT ON COLUMN INDAR_OWN.INDAR_EMPLAZAMIENTO_DATOS.ID_UBICACION IS 'Ubicación geográfica del emplazamiento';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_ESTADO_INST IS 'Estados posibles de las instalaciones';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADO_INST.ID_ESTADO IS 'Clave primaria del estado';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADO_INST.ESTADO IS 'Descripción del estado de la instalación';

COMMENT ON TABLE INDAR_OWN.INDAR_INSTALACION IS 'Instalaciones registradas en el sistema INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_INSTALACION.ID_INSTALACION IS 'Clave primaria de la instalación';
COMMENT ON COLUMN INDAR_OWN.INDAR_INSTALACION.ID_EMPLAZAMIENTO IS 'Emplazamiento de la instalación';
COMMENT ON COLUMN INDAR_OWN.INDAR_INSTALACION.ID_ESTADO_INST IS 'Estado actual de la instalación';
COMMENT ON COLUMN INDAR_OWN.INDAR_INSTALACION.NUMERO IS 'Número de identificación de la instalación';
COMMENT ON COLUMN INDAR_OWN.INDAR_INSTALACION.DATOS_INSTALACION IS 'Datos JSON de la instalación';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_TIPO_EQUIPO IS 'Tipos de equipos registrables en instalaciones';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPO_EQUIPO.ID_TIPO_EQUIPO IS 'Clave primaria del tipo de equipo';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPO_EQUIPO.TIPO IS 'Nombre del tipo de equipo';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_TIPO_EQUIPO.DESCRIPCION IS 'Descripción del tipo de equipo';

COMMENT ON TABLE INDAR_OWN.INDAR_EQUIPOS IS 'Equipos registrados en las instalaciones';
COMMENT ON COLUMN INDAR_OWN.INDAR_EQUIPOS.ID_EQUIPO IS 'Clave primaria del equipo';
COMMENT ON COLUMN INDAR_OWN.INDAR_EQUIPOS.ID_INSTALACION IS 'Instalación a la que pertenece el equipo';
COMMENT ON COLUMN INDAR_OWN.INDAR_EQUIPOS.TIPO_EQUIPO IS 'Tipo de equipo';
COMMENT ON COLUMN INDAR_OWN.INDAR_EQUIPOS.DATOS_EQUIPO IS 'Datos JSON del equipo';

COMMENT ON TABLE INDAR_OWN.INDAR_EXPEDIENTES_INSTALACIONES IS 'Relación entre expedientes e instalaciones';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES_INSTALACIONES.ID_EXPE_INST IS 'Clave primaria de la relación';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES_INSTALACIONES.ID_EXPEDIENTE IS 'Expediente relacionado';
COMMENT ON COLUMN INDAR_OWN.INDAR_EXPEDIENTES_INSTALACIONES.ID_INSTALACION IS 'Instalación relacionada';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_VERSION_PANTALLA_COMP IS 'Versiones de pantallas de tramitación asociadas a componentes';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_PANTALLA_COMP.ID_V_PANTALLA_COMP IS 'Clave primaria de la versión de pantalla de componente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_PANTALLA_COMP.ORDEN IS 'Orden de visualización de la pantalla en el flujo';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_PANTALLA_COMP.ID_PANTALLA IS 'Pantalla de tramitación asociada a esta versión de pantalla de componente';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_PANTALLAS IS 'Maestro de pantallas del sistema INDAR';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_PANTALLAS.ID_PANTALLA IS 'Clave primaria de la pantalla';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_PANTALLAS.NOMBRE IS 'Nombre descriptivo de la pantalla';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_PANTALLAS.DESCRIPCION IS 'Descripción detallada de la pantalla';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_PANTALLAS.FECHA_ALTA IS 'Fecha de creación de la pantalla';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_PANTALLAS.ID_PANTALLA_PADRE IS 'Pantalla padre para estructuras jerárquicas';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS IS 'Flujos de transición entre estados de expedientes';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS.ID_ESTADO_FLUJO IS 'Clave primaria del estado de flujo';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS.ID_V_PANTALLA_COMP IS 'Versión de pantalla de componente asociada al flujo';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS.ID_ESTADO_ACTUAL IS 'Estado actual del expediente en la transición';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS.ID_ESTADO_SIGUIENTE IS 'Estado siguiente al que transiciona el expediente';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS.EVENTO_ENUM IS 'Evento que desencadena la transición de estado';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS.ID_TIPO_DOC IS 'Tipo de documento asociado al evento de transición';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS.ID_USU_REL IS 'Usuario relacionado que ejecuta la acción';

COMMENT ON TABLE INDAR_OWN.INDAR_TM_VERSION_PANTALLAS IS 'Tabla intermedia que relaciona la pantalla con pantalla componente y tiene su pripio JavaScript para la gestion de todos los componentes que tiene la misma';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_PANTALLAS.ID_V_PANTALLA IS 'Clave primaria del permiso';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_PANTALLAS.ID_V_PANTALLA_COMP IS 'Relación con la tabla INDAR_TM_VERSION_PANTALLAS_COMP';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_PANTALLAS.ID_PANTALLA IS 'Relación con la tabla INDAR_TM_PANTALLAS';
COMMENT ON COLUMN INDAR_OWN.INDAR_TM_VERSION_PANTALLAS.JAVASCRIPT IS 'JavaScript que se usa en la pantalla para el control o validación de los distintos componentes que la 