-- Índices INDAR
-- Patrón idempotente: silencia ORA-00955 si el índice ya existe.

-- Índices para INDAR_AUDITORIA_ACCESOS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_AUD_USUARIO" ON "INDAR_OWN"."INDAR_AUDITORIA_ACCESOS" ("ID_USUARIO_REL") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_AUD_FECHA_LOGIN" ON "INDAR_OWN"."INDAR_AUDITORIA_ACCESOS" ("FECHA_LOGIN") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_MENU
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_MENU_PADRE" ON "INDAR_OWN"."INDAR_MENU" ("ID_MENU_PADRE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_MENU_VERSION" ON "INDAR_OWN"."INDAR_MENU" ("ID_VERSION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_MENU_ACTIVO" ON "INDAR_OWN"."INDAR_MENU" ("ACTIVO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_PERSONAS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_PERSONAS_IDENTIFICADOR" ON "INDAR_OWN"."INDAR_PERSONAS" ("IDENTIFICADOR") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_PERSONAS_NOMBRE" ON "INDAR_OWN"."INDAR_PERSONAS" ("NOMBRE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_PERSONAS_EMAIL" ON "INDAR_OWN"."INDAR_PERSONAS" ("EMAIL") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_TM_TIPOS_RELACION
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_TIPOS_REL_CODIGO" ON "INDAR_OWN"."INDAR_TM_TIPOS_RELACION" ("CODIGO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_USUARIOS_RELACIONADOS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_USUREL_PERSONA" ON "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ("ID_PERSONA") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_USUREL_ENTIDAD" ON "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ("ID_RUIAR_ENTIDAD") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_USUREL_TIPO_REL" ON "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ("ID_TIPO_RELACION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_USUREL_ESTADO" ON "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" ("ESTADO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_PERMISOS_REL_VERSION
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_PERM_TIPO" ON "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ("ID_TIPO_RELACION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_PERM_VERSION" ON "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ("ID_VERSION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_PERM_MENU" ON "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ("ID_MENU") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_PERM_ACCION" ON "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" ("ID_ACCION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_ACCIONES
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ACCIONES_TIPO" ON "INDAR_OWN"."INDAR_ACCIONES" ("TIPO_ACCION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ACCIONES_ACTIVO" ON "INDAR_OWN"."INDAR_ACCIONES" ("ACTIVO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_TM_DOC_ESTADOS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_DOC_ESTADOS_NOMBRE" ON "INDAR_OWN"."INDAR_TM_DOC_ESTADOS" ("NOMBRE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_DOC_USUARIOS_REL
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_DOCUSUREL_ESTADO" ON "INDAR_OWN"."INDAR_DOC_USUARIOS_REL" ("ESTADO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_DOCUSUREL_TIPO" ON "INDAR_OWN"."INDAR_DOC_USUARIOS_REL" ("TIPO_DOCUMENTO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_TM_TIPOS_DOC
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_TIPOSDOC_NOMBRE" ON "INDAR_OWN"."INDAR_TM_TIPOS_DOC" ("NOMBRE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_TM_VERSION_COMP
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_VER_COMP_COMPONENTE" ON "INDAR_OWN"."INDAR_TM_VERSION_COMP" ("ID_COMPONENTE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_TM_VERSION_TRAMITES
BEGIN EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX "INDAR_OWN"."UX_VERTRAM_TRAMITE_VER" ON "INDAR_OWN"."INDAR_TM_VERSION_TRAMITES" ("ID_TRAMITE", "VERSION") TABLESPACE "INDAR_DAT"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_EMPLAZAMIENTO_DATOS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_EMPL_DATOS_VER_COMP" ON "INDAR_OWN"."INDAR_EMPLAZAMIENTO_DATOS" ("ID_VERSION_COMP") TABLESPACE "INDAR_DAT"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_EMPL_DATOS_UBICACION" ON "INDAR_OWN"."INDAR_EMPLAZAMIENTO_DATOS" ("ID_UBICACION") TABLESPACE "INDAR_DAT"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_EXPE_COMP_DATOS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_EXPE_COMP_EXPEDIENTE" ON "INDAR_OWN"."INDAR_EXPE_COMP_DATOS" ("ID_EXPEDIENTE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_EXPE_COMP_VERSION" ON "INDAR_OWN"."INDAR_EXPE_COMP_DATOS" ("ID_VERSION_COMP") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
--BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ECD_CAUDAL_GN" ON "INDAR_OWN"."INDAR_EXPE_COMP_DATOS" ("CAUDAL_GN") COMPRESS 1 TABLESPACE "INDAR_DAT"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
--/
--BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ECD_RESULTADO_INSP" ON "INDAR_OWN"."INDAR_EXPE_COMP_DATOS" ("RESULTADO_INSP") COMPRESS 1 TABLESPACE "INDAR_DAT"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
--/

-- Índices para INDAR_INSTALACION
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_INST_EMPLAZAMIENTO" ON "INDAR_OWN"."INDAR_INSTALACION" ("ID_EMPLAZAMIENTO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_INST_ESTADO" ON "INDAR_OWN"."INDAR_INSTALACION" ("ID_ESTADO_INST") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_EQUIPOS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_EQUIPO_INST" ON "INDAR_OWN"."INDAR_EQUIPOS" ("ID_INSTALACION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_EQUIPO_TIPO" ON "INDAR_OWN"."INDAR_EQUIPOS" ("TIPO_EQUIPO") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_TM_VERSION_PANTALLA_COMP
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_VER_PANT_COMP_PANTALLA" ON "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP" ("ID_VERSION_PANT") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_VER_PANT_COMP_VERSION" ON "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP" ("VERSION") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
-- Índices para INDAR_TM_VERSION_PANTALLAS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_VER_PANTALLA_PANT" ON "INDAR_OWN"."INDAR_TM_VERSION_PANTALLAS" ("ID_PANTALLA") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX "INDAR_OWN"."PK_VER_PANTALLA" ON "INDAR_OWN"."INDAR_TM_VERSION_PANTALLAS" ("ID_V_PANTALLA") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
-- Índices para INDAR_TM_PANTALLAS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_TM_PANTALLAS_PADRE" ON "INDAR_OWN"."INDAR_TM_PANTALLAS" ("ID_PANTALLA_PADRE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_TM_ESTADOS_FLUJOS
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ESTADOS_FL_V_PANT_COMP" ON "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ("ID_V_PANTALLA_COMP") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ESTADOS_FL_ESTADO_ACT" ON "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ("ID_ESTADO_ACTUAL") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ESTADOS_FL_ESTADO_SIG" ON "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ("ID_ESTADO_SIGUIENTE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ESTADOS_FL_TIPO_DOC" ON "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ("ID_TIPO_DOC") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IDX_ESTADOS_FL_USU_REL" ON "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" ("ID_USU_REL") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_AGENTES_VERSION
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IX_IAV_AGENTE" ON "INDAR_OWN"."INDAR_AGENTES_VERSION" ("ID_AGENTE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_DOCUMENTO_AGENTES
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IX_IDOC_AGENTE" ON "INDAR_OWN"."INDAR_DOCUMENTO_AGENTES" ("ID_AGENTE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Índices para INDAR_EXP_AGENTES_VER
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IX_IEAV_EXP" ON "INDAR_OWN"."INDAR_EXP_AGENTES_VER" ("ID_EXPEDIENTE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IX_IEAV_AG" ON "INDAR_OWN"."INDAR_EXP_AGENTES_VER" ("ID_AGENTE") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'[CREATE INDEX "INDAR_OWN"."IX_IEAV_AG_VER" ON "INDAR_OWN"."INDAR_EXP_AGENTES_VER" ("ID_AGENTE_VER") TABLESPACE "INDAR_IDX"]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/