CREATE OR REPLACE VIEW INDAR_OWN.V_EXPEDIENTES_DATOS AS
SELECT
    e.ID_EXPEDIENTE,
    e.NUMERO_EXP,
    e.ESTADO                         AS ID_ESTADO,
    est.NOMBRE                       AS NOMBRE_ESTADO,
    e.FECHA_ALTA,
    e.FECHA_FIN,
    mv.COMPONENTES_JSON
FROM
    INDAR_OWN.INDAR_EXPEDIENTES              e
    JOIN  INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE est ON est.ID_ESTADO_EXPEDIENTE    = e.ESTADO
    LEFT JOIN INDAR_OWN.MV_EXPE_COMP_JSON        mv  ON mv.ID_EXPEDIENTE = e.ID_EXPEDIENTE;
/