

-- ============================================================
-- NOTA: El script DDL (INDAR_create_tables.sql) debe ejecutarse
-- conectado directamente como INDAR_OWN, ya que Oracle no permite
-- acotar CREATE/ALTER TABLE a un solo esquema sin privilegios ANY.
--   sqlplus INDAR_OWN/pwd@//host:1532/service @INDAR_create_tables.sql
-- ============================================================

-- Script: GRANTS para tablas principales INDAR
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_AUDITORIA_ACCESOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_CONFIGURATION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_MENU" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_PERSONAS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_TIPOS_RELACION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_USUARIOS_ESTADOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_USUARIOS_RELACIONADOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_DOC_ESTADOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_VERSIONES_APLICACION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_DOC_USUARIOS_REL" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_TIPOS_DOC" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, INSERT, UPDATE, DELETE ON "INDAR_OWN"."INDAR_PERMISOS_REL_VERSION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, INSERT, UPDATE, DELETE ON "INDAR_OWN"."INDAR_ACCIONES" TO "ROL_EXPLOTACION_INDAR";

GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_COMPONENTES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, INSERT, UPDATE, DELETE ON "INDAR_OWN"."INDAR_TM_VERSION_COMP" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, INSERT, UPDATE, DELETE ON "INDAR_OWN"."INDAR_EXPE_COMP_DATOS" TO "ROL_EXPLOTACION_INDAR";


-- GRANTS para secuencias INDAR
GRANT SELECT ON "INDAR_OWN"."SEQ_AUDITORIA_ACCESOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_MENU" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_PERSONAS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_TIPOS_RELACION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_USUARIOS_RELACIONADOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_VERSIONES_APLICACION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_PERMISOS_REL_VERSION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_DOC_USUARIOS_REL" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_ACCIONES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_USU_ESTADOS" TO "ROL_EXPLOTACION_INDAR";

GRANT SELECT ON "INDAR_OWN"."SEQ_COMPONENTES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_VERSION_COMP" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_EXPE_COMP_DATOS" TO "ROL_EXPLOTACION_INDAR";
-- GRANTS para tablas nuevas de ámbitos y trámites
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_AGRUPACIONES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_AMBITOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_TRAMITES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_VERSION_TRAMITES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_TRAMITES_DOCUMENTOS" TO "ROL_EXPLOTACION_INDAR";

-- GRANTS para tablas de expedientes e instalaciones
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_ESTADOS_EXPEDIENTE" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_EXPEDIENTES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_UBICACIONES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_EMPLAZAMIENTO_DATOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_ESTADO_INST" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_INSTALACION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_TIPO_EQUIPO" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_EQUIPOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_EXPEDIENTES_INSTALACIONES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_VERSION_PANTALLA_COMP" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_VERSION_PANTALLAS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_PANTALLAS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_TM_ESTADOS_FLUJOS" TO "ROL_EXPLOTACION_INDAR";

-- GRANTS para tablas de agentes
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_AGENTES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_AGENTES_VERSION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_DOCUMENTO_AGENTES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT, DELETE, INSERT, UPDATE ON "INDAR_OWN"."INDAR_EXP_AGENTES_VER" TO "ROL_EXPLOTACION_INDAR";

-- GRANTS para secuencias nuevas de ámbitos y trámites
GRANT SELECT ON "INDAR_OWN"."SEQ_AGRUPACIONES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_AMBITOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_TRAMITES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_VERSION_TRAMITES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_TRAMITES_DOC" TO "ROL_EXPLOTACION_INDAR";

-- GRANTS para secuencias nuevas de expedientes e instalaciones
GRANT SELECT ON "INDAR_OWN"."SQ_INDAR_EXPEDIENTES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_UBICACIONES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_EMPLAZAMIENTO_DATOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_ESTADO_INST" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_INSTALACION" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_EQUIPOS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_EXPE_INSTALACIONES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_VERSION_PANTALLAS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_VERSION_PANT_COMP" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_TM_PANTALLAS" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SEQ_TM_ESTADOS_FLUJOS" TO "ROL_EXPLOTACION_INDAR";

-- GRANTS para secuencias de agentes
GRANT SELECT ON "INDAR_OWN"."SQ_INDAR_AGENTE" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SQ_INDAR_AGENTES_VER" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SQ_INDAR_DOCUMENTO_AGENTES" TO "ROL_EXPLOTACION_INDAR";
GRANT SELECT ON "INDAR_OWN"."SQ_INDAR_EXP_AG_VER" TO "ROL_EXPLOTACION_INDAR";
-- GRANTS para vistas materializadas INDAR
GRANT SELECT ON "INDAR_OWN"."MV_EXPE_COMP_JSON" TO "ROL_EXPLOTACION_INDAR";
-- GRANTS para vistas INDAR
GRANT SELECT ON "INDAR_OWN"."V_EXPEDIENTES_DATOS" TO "ROL_EXPLOTACION_INDAR";

-- GRANTS para usuarios del esquema INDAR_OWN
GRANT ROL_EXPLOTACION_INDAR TO MGBURILLO;
GRANT ROL_EXPLOTACION_INDAR TO SKT_USR;