REM INSERTING into INDAR_OWN.INDAR_ACCIONES
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_ACCIONES (ID_ACCION,TIPO_ACCION,DESCRIPCION,ACTIVO) values ('1','VISUALIZAR_MENU','Permite visualizar los men�s','1');
Insert into INDAR_OWN.INDAR_ACCIONES (ID_ACCION,TIPO_ACCION,DESCRIPCION,ACTIVO) values ('2','CREAR','Permite crear nuevos registros en el sistema','1');
Insert into INDAR_OWN.INDAR_ACCIONES (ID_ACCION,TIPO_ACCION,DESCRIPCION,ACTIVO) values ('3','EDITAR','Permite modificar registros existentes','1');
Insert into INDAR_OWN.INDAR_ACCIONES (ID_ACCION,TIPO_ACCION,DESCRIPCION,ACTIVO) values ('4','ELIMINAR','Permite eliminar registros del sistema','1');
REM INSERTING into INDAR_OWN.INDAR_AUDITORIA_ACCESOS
SET DEFINE OFF;
REM INSERTING into INDAR_OWN.INDAR_CONFIGURATION
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Key','Path','/compartido/app/indarbk/hmac.key','URL firma y verificable CSV','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','ApplicationId','CCSV','Applitacion ID de CCSV','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','Proceedings','https://preaplicaciones.aragon.es:443/ccsv_core/services/AdministrativeFileWS','URL del servicio CSV expediente','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','Host','https://preaplicaciones.aragon.es:443/ccsv_core/services/DocumentMetadataSignatureWS','URL del servicio CSV documentos','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Host','Master','172.27.37.20','Establecido a Tue Jan 27 05:23:08 CET 2026','5');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Host','Nodes','10.250.103.49@10.250.104.220@10.250.113.208@172.28.208.1@10.250.101.89@172.25.128.1@10.250.118.248@10.250.102.99@10.250.102.30@192.168.1.138@172.20.192.1@172.31.48.1@10.250.104.206@192.168.0.14@10.250.100.246@10.250.113.186@192.168.1.133@10.50.1.23@10.250.117.223@192.168.0.19@10.50.1.47@172.27.37.20@192.168.1.186@192.168.1.21@192.168.1.20','Insertado el nodo maestro 172.27.37.38','5');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Img','Path','/compartido/app/indarbk/img/','Ruta de las imagenes','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Internal','Url','https://desaplicaciones.aragon.es/indar','Url Frontal CORS','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Ip','Nodo','172.27.37.38','Ip conexion PRE servicion gestSntEstado','5');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Jwt','Expiration','60000','Tiempo de expiracion de JWT','2');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Mfe','Address','https://preaplicaciones.aragon.es/mfe_core','Url MFE','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Indar','ApplicationId','INDARBK','Application ID de INDAR','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','Validate','https://preaplicaciones.aragon.es/ccsv_pub','URL firma y verificable CSV','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','ORG','ORG18169','Organismo del servicio de industria','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','NameService','SERVICIO DE METROLOGIA, SEGURIDAD Y CALIDAD INDUSTRIAL','Nombre del servicio de industria','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','GenerateAliasFile','INDR','Alias con el que se genera el nombre de los documentos que se suben a CCSV','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','NifDefault','00000000T','NIF que se utiliza para enviar a CCSV','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','CSV','ProdCodigo','2158','Código de procedimiento por defecto para subir documentos a CCSV','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Compartido','Path','/compartido/app/indarbk/','Ruta carpeta compartida en el servidor para INDAR','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Key','PathLocal','C:/compartido/app/indarbk/hmac.key','URL firma y verificable CSV','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Img','PathLocal','C:/compartido/app/indarbk/img/','Ruta de las imagenes','1');
Insert into INDAR_OWN.INDAR_CONFIGURATION (COMPONENT,TYPE,PROPERTY,VALUE,DESCRIPTION,SORT) values ('CORE','Compartido','PathLocal','C:/compartido/app/indarbk/','Ruta carpeta compartida en el servidor para INDAR','1');
REM INSERTING into INDAR_OWN.INDAR_VERSIONES_APLICACION
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_VERSIONES_APLICACION (ID_VERSION,NUMERO_VERSION,DESCRIPCION,FECHA_VERSION,ACTIVO) values ('1','1','Versi�n inicial',to_date('11/12/2025','DD/MM/YYYY'),'1');
REM INSERTING into INDAR_OWN.INDAR_MENU
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('1','Inicio','Men� principal','1','1','/home',null,'1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('2','Expedientes','Gesti�n de expedientes','2','1','/expedientes',null,'1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('3','Instalaciones','Gesti�n de instalaciones','3','1','/instalaciones',null,'1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('4','Administraci�n','Opciones de administraci�n','5','1','/admin',null,'1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('5','Ayuda','Ayuda y documentaci�n','7','1','https://ayuda.aragon.es',null,'1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('6','Soporte','Soporte t�cnico','8','1','https://soporte.aragon.es',null,'1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('7','Usuarios','Gesti�n de usuarios','1','1','/admin/usuarios','4','1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('8','B�squeda de expedientes','B�squeda de expedientes','1','1','/expedientes/busqueda','2','1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('9','B�squeda de instalaciones','B�squeda de instalaciones','1','1','/instalaciones/busqueda','3','1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('10','Maestros','Acceso a pantalla de Maestros para la gesti�n de la aplicaci�n','6','1','/maestros',null,'1');
Insert into INDAR_OWN.INDAR_MENU (ID_MENU,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,URL,ID_MENU_PADRE,ID_VERSION) values ('11','Informes','Informes y reportes','4','1','/informes',null,'1');
REM INSERTING into INDAR_OWN.INDAR_PERSONAS
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_PERSONAS (ID_PERSONA,TIPO_IDENTIFICADOR,IDENTIFICADOR,NOMBRE,APELLIDO1,APELLIDO2,NOMBRE_COMPLETO,EMAIL,TELEFONO,TIPO_PERSONA,FECHA_ALTA,FECHA_MODIFICACION,FUENTE_ORIGEN,ACTIVO,TEMPORAL) values ('1','DNI','73214004J','Alex','Ventura','Almolda','Alex Ventura Almolda',null,null,'FISICA',to_date('10/12/2025','DD/MM/YYYY'),to_date('10/12/2025','DD/MM/YYYY'),'INDARBK','1','0');
REM INSERTING into INDAR_OWN.INDAR_TM_DOC_ESTADOS
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_DOC_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('1','ACEPTADO','Documento aceptado');
Insert into INDAR_OWN.INDAR_TM_DOC_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('2','RECHAZADO','Documento rechazado');
Insert into INDAR_OWN.INDAR_TM_DOC_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('3','PENDIENTE VALIDAR','Documento pendiente de validaci�n');
Insert into INDAR_OWN.INDAR_TM_DOC_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('4','FIRMADO','Documento firmado');
Insert into INDAR_OWN.INDAR_TM_DOC_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('5','SELLADO','Documento sellado');
Insert into INDAR_OWN.INDAR_TM_DOC_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('6','PENDIENTE DE FIRMA','Documento pendiente de firma');
Insert into INDAR_OWN.INDAR_TM_DOC_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('7','BORRADO','Documento borrado');
REM INSERTING into INDAR_OWN.INDAR_TM_TIPOS_DOC
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_TIPOS_DOC (ID_TIPO_DOC,NOMBRE,DESCRIPCION) values ('1','DR','Documento de representaci�n');
Insert into INDAR_OWN.INDAR_TM_TIPOS_DOC (ID_TIPO_DOC,NOMBRE,DESCRIPCION) values ('2','DD','Documento de delegado');
REM INSERTING into INDAR_OWN.INDAR_TM_TIPOS_RELACION
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('1','ADMIN','ADMIN','ADMIN','0','0','0','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('2','TIT','Titular','Titular','0','0','3','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('3','DEL','Delegado','Delegado de titular','0','0','3','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('4','REPT','Representante','Representante de titular','0','0','3','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('5','REPO','Representante','Representante de Organismo de control','0','0','1','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('6','REPE','Representante','Representante de empresa','0','0','2','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('7','TECO','T�cnico','Tecnico de Organismo de control','0','0','1','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('8','ADME','Administrativo','Administrativo de empresa','0','0','2','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('9','ADMO','Administrativo','Administrativo de Organismo de control','0','0','1','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('10','TRA','Tramitador','Tramitador','0','0','5','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('11','JSEC','Jefe de secci�n','Jefe de seccion','0','0','5','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('12','SERCEN','Servicios Centrales','Servicios Centrales','0','0','6','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('13','CONT','Consultor Titular','Consultor Titular','0','0','3','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('14','JADMO','Administrativo Jefe','Administrativo Jefe de Organismo de control','0','0','1','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('15','TECE','T�cnico','Tecnico de empresa','0','0','2','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('16','EMPREI','Empresa Instaladora','Empresa Instaladora','0','0','4','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('17','EMPREM','Empresa mantenedora','Empresa mantenedora','0','0','2','1');
Insert into INDAR_OWN.INDAR_TM_TIPOS_RELACION (ID_TIPO_RELACION,CODIGO,NOMBRE,DESCRIPCION,REQUIERE_MAESTRO,REQUIERE_APROBACION,NIVEL_JERARQUICO,ACTIVO) values ('18','OCA','Organismo de control','Organismo de control','0','0','1','1');
REM INSERTING into INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('1','ACTIVO','ACTIVO');
Insert into INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('2','BAJA','BAJA');
Insert into INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('3','PENDIENTE','PENDIENTE');
Insert into INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('4','BLOQUEADO','BLOQUEADO');
Insert into INDAR_OWN.INDAR_TM_USUARIOS_ESTADOS (ID_ESTADO,NOMBRE,DESCRIPCION) values ('5','RECHAZADO','RECHAZADO');
REM INSERTING into INDAR_OWN.INDAR_USUARIOS_RELACIONADOS
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_USUARIOS_RELACIONADOS (ID_USUARIO_INDAR,ID_PERSONA,ID_RUIAR_ENTIDAD,ID_TIPO_RELACION,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_APROBACION,USUARIO_APROBACION,MOTIVO_BAJA,MFE_ULTIMA_SYNC,MFE_TOKEN_HASH) values ('1','1',null,'1','1',to_date('10/12/2025','DD/MM/YYYY'),null,to_date('10/12/2025','DD/MM/YYYY'),'0',null,null,null);
REM INSERTING into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('1','CREADO','Expediente creado, pendiente de asignación de ubicación','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('2','PENDIENTE DE UBICACIÓN','Expediente pendiente de determinar su ubicación','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('3','PENDIENTE DE INSTALACIÓN','Expediente pendiente de instalación física','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('4','INSTALACIÓN SOLICITADA','Se ha solicitado la instalación del expediente','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('5','INSTALACIÓN APROBADA','La instalación del expediente ha sido aprobada','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('6','INSTALACIÓN DENEGADA','La instalación del expediente ha sido denegada','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('7','PENDIENTE DE DATOS','Expediente pendiente de completar datos','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('8','PENDIENTE DE DOCUMENTACIÓN','Expediente pendiente de adjuntar documentación','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('9','PENDIENTE DE FIRMA','Expediente pendiente de firma electrónica','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('10','PENDIENTE DE ENTREGA A DGA','Expediente preparado y pendiente de entrega a DGA','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('11','PENDIENTE DE SELLADO','Expediente pendiente de sellado oficial','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('12','PENDIENTE DE TRASLADO','Expediente pend. de traslado a organismo destino','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('13','TRASLADO EN EJECUCIÓN','Expediente en proceso de traslado','1');
Insert into INDAR_OWN.INDAR_TM_ESTADOS_EXPEDIENTE (ID_ESTADO_EXPEDIENTE,NOMBRE,DESCRIPCION,ACTIVO) values ('14','TRASLADADO A RUI','Expediente trasladado al Registro Único Industrial','1');
REM INSERTING into INDAR_OWN.INDAR_TM_PANTALLAS
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_PANTALLAS (ID_PANTALLA,NOMBRE,DESCRIPCION,FECHA_ALTA,ID_PANTALLA_PADRE) values (INDAR_OWN.SEQ_TM_PANTALLAS.NEXTVAL,'Selección de ámbito','Pantalla de introducción donde se debe indicar el ámbito del expediente',to_date('10/03/2026','DD/MM/YYYY'),null);
Insert into INDAR_OWN.INDAR_TM_PANTALLAS (ID_PANTALLA,NOMBRE,DESCRIPCION,FECHA_ALTA,ID_PANTALLA_PADRE) values (INDAR_OWN.SEQ_TM_PANTALLAS.NEXTVAL,'Ubicación','Pantalla donde se debe seleccionar la ubicación del expediente o crearla',to_date('10/03/2026','DD/MM/YYYY'),null);
REM INSERTING into INDAR_OWN.INDAR_TM_VERSION_PANTALLAS
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_VERSION_PANTALLAS (ID_V_PANTALLA,ID_PANTALLA,ID_V_PANTALLA_COMP,JAVASCRIPT) values (INDAR_OWN.SEQ_VERSION_PANTALLAS.NEXTVAL,1,null,null);
Insert into INDAR_OWN.INDAR_TM_VERSION_PANTALLAS (ID_V_PANTALLA,ID_PANTALLA,ID_V_PANTALLA_COMP,JAVASCRIPT) values (INDAR_OWN.SEQ_VERSION_PANTALLAS.NEXTVAL,2,null,null);
REM INSERTING into INDAR_OWN.INDAR_TM_VERSION_PANTALLA_COMP
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_VERSION_PANTALLA_COMP (ID_V_PANTALLA_COMP,VERSION,ORDEN,ID_VERSION_PANTALLA,ID_VERSION_COMPONENTE) values (INDAR_OWN.SEQ_VERSION_PANT_COMP.NEXTVAL,1,1,1,1);
Insert into INDAR_OWN.INDAR_TM_VERSION_PANTALLA_COMP (ID_V_PANTALLA_COMP,VERSION,ORDEN,ID_VERSION_PANTALLA,ID_VERSION_COMPONENTE) values (INDAR_OWN.SEQ_VERSION_PANT_COMP.NEXTVAL,1,2,1,1);
REM INSERTING into INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS
SET DEFINE OFF;
Insert into INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS (ID_ESTADO_FLUJO,ID_V_PANTALLA_COMP,ID_ESTADO_ACTUAL,ID_ESTADO_SIGUIENTE,EVENTO_ENUM,ID_TIPO_DOC,ID_USU_REL) values (INDAR_OWN.SEQ_TM_ESTADOS_FLUJOS.NEXTVAL,1,1,2,'',null,null);
Insert into INDAR_OWN.INDAR_TM_ESTADOS_FLUJOS (ID_ESTADO_FLUJO,ID_V_PANTALLA_COMP,ID_ESTADO_ACTUAL,ID_ESTADO_SIGUIENTE,EVENTO_ENUM,ID_TIPO_DOC,ID_USU_REL) values (INDAR_OWN.SEQ_TM_ESTADOS_FLUJOS.NEXTVAL,1,2,3,'',null,null);
COMMIT;